{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsscience.fullname" . }}-admin
  labels:
    {{- include "dnsscience.admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dnsscience.admin.selectorLabels" . | nindent 4 }}
{{- end }}
