{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dnsscience.fullname" . }}-api
  labels:
    {{- include "dnsscience.api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "dnsscience.api.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
